#!/usr/bin/env bash

if [$# -le 3]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	FILE_PATH=$1
	SERVER_IP=$2
	USERNAME=$3
	SSH_KEY=$4
	
	ssh-keygen -R "$SERVER_IP"
	scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME"@"$SERVER_IP":~/
fi
