#!/usr/bin/env bash
# Script: 1-debugging_made_short
# Description: Configures Nginx to listen on port 80 for all active IPv4 IPs.

sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
kill -9 "$(cat /var/run/nginx.pid)"
