#!/usr/bin/env bash
#displays PID with the process name


for pid in /proc/[0-9]*/cmdline; do
    if grep -q -i "bash" "$pid"; then
        process_pid=$(basename "$(dirname "$pid")")
        process_name=$(tr -d '\0' < "$pid")
        echo "$process_pid   $process_name"
    fi
done
