#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd using the while loop + IFS.

# Use IFS to set the field separator to ":" for parsing /etc/passwd
IFS=":"

# Read the file /etc/passwd line by line
while read -r username _ uid gid info home_dir shell; do
    # Extract the gang and passcode information from the info field
    gang=$(echo "$info" | cut -d',' -f1)
    passcode=$(echo "$info" | cut -d',' -f2)

    # Display the information in the required format
    echo "The user $username is part of the $gid gang, lives in $home_dir and rides $shell. $uid's place is protected by the passcode $passcode, more info about the user here: $info"
done < /etc/passwd
