#!/usr/bin/env bash
# This script displays the visitor IP along with the HTTP status code from the Apache log file

# Use awk to process the Apache log file and display the data in the specified format
awk '{print $1, $9}' apache-access.log
