#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

# Initialize a counter variable
count=0

# Loop using while until count reaches 10
while [ $count -lt 10 ]; do
    echo "Best School"
    # Increment the counter
    ((count++))
done
