#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

# Initialize a counter variable
count=0

# Loop using until until count becomes 10
until [ $count -eq 10 ]; do
    echo "Best School"
    # Increment the counter
    ((count++))
done
