#!/bin/bash

# Get all active network interfaces
active_interfaces=$(ip addr show | awk '/inet / {print $NF}')

# Iterate through the interfaces and display IPv4 addresses
for interface in $active_interfaces; do
  ipv4=$(ip addr show $interface | awk '/inet / {print $2}')
  echo "$ipv4"
done

